name: ng2_autogrow
description: Autogrow textarea directive for Angular 2 Dart.
author: Kasper Peulen <kasperpeulen@gmail.com>
version: 0.0.0
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: '^2.0.0-beta.0'
dev_dependencies:
  angular2_testing: '^2.0.0-beta.0'
  test: '^0.12.6+2'
  grinder: '^0.8.0+1'
  coverage: '^0.7.2'
  dart_style: '^0.2.1'
  browser: '^0.10.0+2'
  git: '^0.4.4+2'
